global:
  environment: production

web:
  replicaCount: 2
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 70
  ratelimitDefault: "100000 per minute"

vpa:
  enabled: true

# OPC UA Security — включаем SignAndEncrypt в проде.
# Требует certs-secrets.yaml с base64-сертификатами.
opcSecurity:
  mode: "None"

ingress:
  enabled: false