apiVersion: v1
kind: Secret
metadata:
  name: opc-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opc-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  ADMIN_USER: {{ .Values.secrets.adminUser | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  EMAIL_PASSWORD: {{ .Values.secrets.emailPassword | quote }}
  GRAFANA_PASSWORD: {{ .Values.secrets.grafanaPassword | quote }}
