apiVersion: v1
kind: ServiceAccount
metadata:
  name: opc-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opc-monitor.labels" . | nindent 4 }}
automountServiceAccountToken: false
